version: "3.5"

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 15672:15672
      - 5672:5672
    networks: 
      - microservices
  
networks: 
  microservices:
    name: network_microservices

